### ISSUE TITLE
Falsche Navigation von Home Button und Bild

### ISSUE THREAD

**Issue by oglis22** [Arasia-net/Arasia-Website#1]
wenn man auf den home button oder auf das bild clickt, wird man zu / weitergeleitet aber die website läuft ja auf /Arasia-Website deshlan müsste man im code statt auf herf="/" auf href="/Arasie-Website" verweisen. Oder direkt auf eine file z.b. index.html

![Screenshot 2024-06-26 224149](https://github.com/Arasia-net/Arasia-Website/assets/119761510/16157896-4bb4-4c63-9f5f-45c2872fa89d)

**Comment by J4nas** [comment]
Ja musste ich noch anpassen. Gemacht!
